### ISSUE TITLE
API gives redirect to failing URL

### ISSUE THREAD

**Issue by bomeara** [CSTARS/ecosis#1]
I tried doing

`curl http://ecosis.org/rest/query?text=&filters=[]&start=0&end=6`

as suggested at http://cstars.github.io/ecosis/ . However, I get back:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://ecosis.orgrest/query?text=">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at ecosis.org Port 80</address>
</body></html>
```

However, https://ecosis.orgrest/ is clearly not a working URL.

**Comment by jrmerz** [comment]
Thanks for the heads up.  Looks like the HTTPS redirect is broken.  I'll take a look, for now you can use: https://ecosis.org/mqe/query?text=&filters=%5B%5D&start=0&stop=6

FYI.  at the bottom of every search page on ecosis.org, there is a link to the API call for that page.

**Comment by bomeara** [comment]
Great, thank you. Btw, my first exposure to EcoSiS was from Phil Townsend at a NIMBioS working group -- seems like a very useful tool, and kudos on it being so open.

**Comment by jrmerz** [comment]
@bomeara Thanks!  Open has been the keyword the entire time.

I have updated the docs (thanks again for pointing out the issue) as well as fixed the https redirect.  Let me know if anything is still broken on your end and I will reopen issue.

FYI, the 'correct' url for package queries:
https://ecosis.org/package/query?text=&filters=[]&start=0&end=6
Then to grab a package:
https://ecosis.org/package/get?id=de0a18b5-fe16-4ae1-9e27-a662578310d2
