### ISSUE TITLE
Chrome original dataset resources not downloading

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#26]
Under the following titles are the original dataset resources not downloading. When the link is clicked a new window in Chrome is opened and reads "This site cannot be reached"

**Comment by walther3** [comment]
Titles: Superscripts test, Empty fields test, Fresh test metadata fields, Time series test, and Formatting time series data.

**Comment by walther3** [comment]
In windows operating system

**Comment by jrmerz** [comment]
duplicate #35
