### ISSUE TITLE
Garaba Test1 Spectra

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#27]
When right clicking through the 3 spectra you can right click from 1 to 2, but going from 2 to 3 it takes you back to spectra 1. But when left clicking you can go from 1 to 3 to 2 back to 1.

**Comment by walther3** [comment]
this issue is occurring in both Chrome and Firefox on windows devices.

**Comment by walther3** [comment]
Also is occurring on windows operating system with Internet Explorer

**Comment by jrmerz** [comment]
pushed to dev.  please reopen if still an issue.
