### ISSUE TITLE
Linked Resources under Superscripts test

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#28]
Under linked sources in the superscripts test there is a link (paper.com) and when it is clicked on it opens the screen that I have attached. 
![Capture](https://user-images.githubusercontent.com/55326013/64911414-2e0e7680-d6e7-11e9-8f84-46ffcb218522.PNG)

**Comment by walther3** [comment]
In windows operating system

**Comment by jrmerz** [comment]
pushed to dev.  please reopen if still an issue.
