### ISSUE TITLE
Firefox issues with original dataset resources downloads

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#29]
The following titles will not allow for links under "original dataset resources" to be downloaded, located under the download tab at top of the pages. New tab in Fire fox will open and say, "Hmm. We're having trouble finding that site." Titles: Empty fields, fresh test metadata fields, superscripts test, time series test, formatting time series test.

**Comment by walther3** [comment]
In windows operating system

**Comment by jrmerz** [comment]
duplicate issue #35
