### ISSUE TITLE
Dataset commits (push) no longer successfully being published

### ISSUE THREAD

**Issue by serbinsh** [CSTARS/ecosis#3]
First, let me say I am not sure if I should post this here or at:
https://github.com/EcoSIS

Second, I tried sending this issue to help@ecospectra.org and the email bounced back.  As such, I will replicate the question here:

I have a fairly large dataset of spectra, traits, and other ancillary data/photos that I am working on compiling to share via EcoSIS.  The name is ```NASA HyspIRI Airborne Campaign Leaf and Canopy Spectra and Leaf Traits```  I had been successfully committing (pushing) updates but over the last few days my efforts to publish the changes are failing and the dataset no longer shows up on ecosis.org.  I have finished uploading the spectra and spectra metadata, I just need to refine my trait datasets with trait names that match expectation and I will be complete.  However I would like to make sure what I have so far loads and displays correctly.  Do you have any ideas about why the dataset is not longer successfully getting published when requested?  When I am editing the dataset and go to the "Publish" tab the spectra and meta-data loads fine.

**Comment by serbinsh** [comment]
Sorry, I meant to post the email error here as well:


```
The following message to <help@ecospectra.org> was undeliverable.
The reason for the problem:
5.1.2 - Bad destination host 'DNS Hard Error looking up ecospectra.org (MX):  NXDomain'
Reporting-MTA: dns; smtpout4.bnl.gov

Final-Recipient: rfc822;help@ecospectra.org
Action: failed
Status: 5.0.0 (permanent failure)
Diagnostic-Code: smtp; 5.1.2 - Bad destination host 'DNS Hard Error looking up ecospectra.org (MX):  NXDomain' (delivery attempts: 0)

From: "Serbin, Shawn" <sserbin@bnl.gov>
Subject: Dataset commits no longer successfully being pushed
Date: April 2, 2018 at 10:16:26 AM EDT
To: "help@ecospectra.org" <help@ecospectra.org>
```

**Comment by jrmerz** [comment]
First, this is the correct place to create tickets for ecosis.  And the help email is help@ecosis.org though a ticket is preferred.  Where did you see help@ecospectra.org?  If there is a lingering reference, it should be changed.

As for your dataset issues, let me inspect and I will get back to you.

**Comment by serbinsh** [comment]
@jrmerz Thanks!  For the life of me I cannot find help@ecospectra.org anywhere but I recall clicking on the link on the ecosis.org page?  Not sure how that is since now when I view that page the correct email address shows up.  Weird.  

I did find another broken link.  If you click "About" in the data management portal you go here:

```
Data maintainers should use this application to maintain and publish their data to EcoSIS Search.

You can find tutorials and resources here: tutorial.ecosis.org

Want to practice using the data management tool? Try out the EcoSIS Sandbox!. You can even push to a sandbox for search.
```

And the sandbox link goes to: http://dev-data.ecospectra.org/  which doesnt work. As well as http://dev-search.ecospectra.org/


Second, let me know if I can provide any additional info to help isolate what might be going on.

**Comment by serbinsh** [comment]
Sorry for spamming this thread but I just found where ecospectra shows up.  For example, if you view a dataset such as:  https://ecosis.org/#result/7ee28ae9-24c6-459c-a4be-1fbf78a609c8

and scroll to the bottom:

![screen shot 2018-04-02 at 10 55 01 am](https://user-images.githubusercontent.com/3067369/38200959-6404d790-3664-11e8-823d-848c4906cedd.png)

![screen shot 2018-04-02 at 10 55 51 am](https://user-images.githubusercontent.com/3067369/38200964-6bdaca10-3664-11e8-8d67-b1ea204271e0.png)


I'm not sure if there is where I found the link before but that is at least one place where it needs to change?

**Comment by jrmerz** [comment]
Ok, thanks! And never spam, help fixing issues is always appreciated.  I have logged the ecospectra issue here #4 .

As for publishing dataset dd94f09c-1794-44f4-82e9-a7ca707a1ec0, I have confirmed it is failing.  It will take me a little time to diagnose the bug.  I will try and get to it tonight.

**Comment by jrmerz** [comment]
@serbinsh Just an update for you.  I am dealing with some vm issues with ecosis that are preventing me for diagnosing the bug.  Unfortunately I don't think the vm issue is the cause of the bug... I will address this once the machine is happy again (hopefully soon).

**Comment by serbinsh** [comment]
No problem @jrmerz Also, when you have that working again I may need some guidance on how best to link all the data together. Another issue I am having is that spectra and metadata link fine but I can't then successfully link ancillary data based on aa common field.  Maybe that is another issue I should post instead of wrapping here, but wasn't sure if they might be connected.....

**Comment by jrmerz** [comment]
So looks like there was two issues.  First, you have switched lat/lng values in some of your metadata, this was breaking the geoindex in the database and causing the push to fail.  To compound the situation, you have some unicode values in your data that (apparently) python can't print, so error logging was failing.  I have fixed the second issue, so you should receive an email on a failed push now.  I will leave it up to you to fix the first.

**Comment by jrmerz** [comment]
to be honest, I already deleted my debug notes and the server is now catching the db error log correctly (which is really long for this project).  In the past we have seen unicode w/ degree marks or the correct micro character.

FYI, unicode is supported.  Just hit a bug where it was causing an issue.
