### ISSUE TITLE
Filter by location in Explorer, not working

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#30]
Must scroll half way down page for any sort of image to start to show (image attached is all that it would load), locate me button does not work. Says "user denied 
![Capture1](https://user-images.githubusercontent.com/55326013/64911590-6d3dc700-d6e9-11e9-8ad6-4f448284da4d.PNG)
the request for Geo location"

**Comment by jrmerz** [comment]
pushed to dev.  please reopen if still an issue.
