### ISSUE TITLE
Windows Explorer wavelength and reflectance issue

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#31]
Boxes for wavelength and reflectance are not expanded so you cannot see the values in them. 
![Capture2](https://user-images.githubusercontent.com/55326013/64911734-205af000-d6eb-11e9-9ee4-ae094674c200.PNG)

**Comment by jrmerz** [comment]
IE 11

**Comment by jrmerz** [comment]
pushed to dev.  please reopen if still an issue.
