### ISSUE TITLE
New bug using the API in R - looks like the ecosis URL changes?

### ISSUE THREAD

**Issue by serbinsh** [CSTARS/ecosis#37]
Hello

This could be a somewhat serious issue I am having with my existing R code using EcoSIS data.  I have been using code like this to get ecosis data into R:

```
#--------------------------------------------------------------------------------------------------#
### Grab data
print("**** Downloading Ecosis data ****")
ecosis_id <- "13aef0ce-dd6f-4b35-91d9-28932e506c41"  # lopex
ecosis_file <- sprintf(
  "https://ecosis.org/package/export?package_id=%s&filters=&metadata=true",
  ecosis_id
)

message("Downloading data...")
dat_raw <- read_csv(ecosis_file)
message("Download complete!")

# keep just fresh leaf refl obs. remove dried leaves from sample set
remove <- c(176,177,178,179,180,196,197,198,199,200,321,322,323,324,325)
remove <- which(dat_raw$Measurement_type=="transmittance" | dat_raw$`Sample_#` %in% remove)
lopex_dat_clean <- dat_raw[-remove,]

ecosis_id <- "2231d4f6-981e-4408-bf23-1b2b303f475e"  # angers
ecosis_file <- sprintf(
  "https://ecosis.org/package/export?package_id=%s&filters=&metadata=true",
  ecosis_id
)
message("Downloading data...")
dat_raw <- read_csv(ecosis_file)
message("Download complete!")

# cleanup and remove dried leaves from dataset
remove <- c(178,179,184,185,196,197,241,250,254,257,258,269)
remove <- which(dat_raw$Measurement_type=="transmittance" | dat_raw$`Sample_#` %in% remove)
angers_dat_clean <- dat_raw[-remove,]

rm(dat_raw)
#--------------------------------------------------------------------------------------------------#

```

I use this, for example, in a recently published paper.  See here:  https://github.com/serbinsh/SSerbin_etal_2019_NewPhytologist . and here:  https://github.com/serbinsh/SSerbin_etal_2019_NewPhytologist/blob/master/nph16123-sup-0002-MethodsS1.R

BUT since recent changes to EcoSIS, like within the last week or two, this no longer works??

```
[1] "**** Downloading Ecosis data ****"
Downloading data...
Parsed with column specification:
cols(
  `<!DOCTYPE html>` = col_character()
)
Warning: 811 parsing failures.
row col           expected    actual                                                                                                       file
 11  -- 1 columns          3 columns 'https://ecosis.org/package/export?package_id=13aef0ce-dd6f-4b35-91d9-28932e506c41&filters=&metadata=true'
 30  -- 1 columns          2 columns 'https://ecosis.org/package/export?package_id=13aef0ce-dd6f-4b35-91d9-28932e506c41&filters=&metadata=true'
 32  -- delimiter or quote ]         'https://ecosis.org/package/export?package_id=13aef0ce-dd6f-4b35-91d9-28932e506c41&filters=&metadata=true'
 32  -- delimiter or quote c         'https://ecosis.org/package/export?package_id=13aef0ce-dd6f-4b35-91d9-28932e506c41&filters=&metadata=true'
 32  -- delimiter or quote :         'https://ecosis.org/package/export?package_id=13aef0ce-dd6f-4b35-91d9-28932e506c41&filters=&metadata=true'
... ... .................. ......... ............................................................................. [... truncated]
Download complete!
Downloading data...
Parsed with column specification:
cols(
  `<!DOCTYPE html>` = col_character()
)
Warning: 811 parsing failures.
row col           expected    actual                                                                                                       file
 11  -- 1 columns          3 columns 'https://ecosis.org/package/export?package_id=2231d4f6-981e-4408-bf23-1b2b303f475e&filters=&metadata=true'
 30  -- 1 columns          2 columns 'https://ecosis.org/package/export?package_id=2231d4f6-981e-4408-bf23-1b2b303f475e&filters=&metadata=true'
 32  -- delimiter or quote ]         'https://ecosis.org/package/export?package_id=2231d4f6-981e-4408-bf23-1b2b303f475e&filters=&metadata=true'
 32  -- delimiter or quote c         'https://ecosis.org/package/export?package_id=2231d4f6-981e-4408-bf23-1b2b303f475e&filters=&metadata=true'
 32  -- delimiter or quote :         'https://ecosis.org/package/export?package_id=2231d4f6-981e-4408-bf23-1b2b303f475e&filters=&metadata=true'
... ... .................. ......... ............................................................................. [... truncated]
Download complete!
Error: Can't find columns NA, NA, NA, NA, NA, … (and 1896 more) in `.data`.
Call `rlang::last_error()` to see a backtrace
In addition: Warning messages:
1: Unknown or uninitialised column: 'Measurement_type'. 
2: Unknown or uninitialised column: 'Sample_#'. 
3: Unknown or uninitialised column: 'Measurement_type'. 
 Show Traceback
 
 Rerun with Debug
 Error: Can't find columns NA, NA, NA, NA, NA, … (and 1896 more) in `.data`.
Call `rlang::last_error()` to see a backtrace 
```

THis is a problem as this breaks the code I provided to a recent manuscripts supplemental info.  Can you confirm this is a bug or is this a fundamental change to accessing data from EcoSIS?  If the later I am going to have to see if I can sent a correction to the journal with the new way to get data.  Could you please let me know what that might be or the best way moving forward?  I have been utilizing the IDs in my code and this means I need to change all of that.

**Comment by serbinsh** [comment]
If I change to the new API I get this:

```
> ecosis_file <- sprintf('https://ecosis.org/api/package/angers-leaf-optical-properties-database--2003-')
> ecosis_file
[1] "https://ecosis.org/api/package/angers-leaf-optical-properties-database--2003-"
> dat_raw <- read_csv(ecosis_file)
Parsed with column specification:
cols(
  .default = col_character()
)
See spec(...) for full column specifications.
Warning message:
Duplicated column names deduplicated: 'type":"upload' => 'type":"upload_1' [2113], 'type":"upload' => 'type":"upload_2' [2116], 'type":"upload' => 'type":"upload_3' [2119] 
```

**Comment by serbinsh** [comment]
Also, it looks like the LOPEX foundational dataset has disappeared? Can you confirm this as well?  Why would that be removed as it was used as an example in my paper

**Comment by serbinsh** [comment]
Interesting this still does resolve properly to the data page:  https://ecosis.org/#result/2231d4f6-981e-4408-bf23-1b2b303f475e  (angers)

as does this, https://ecosis.org/package/13aef0ce-dd6f-4b35-91d9-28932e506c41, but I wasnt able to find lopex in the search?

**Comment by serbinsh** [comment]
```
> traceback()
10: stop(cnd)
9: abort(error_unknown_names(unknown_names))
8: check_names_before_after_character(j, names(unclass(x)))
7: check_names_df(j, x)
6: `[.tbl_df`(lopex_dat_clean, , names(lopex_dat_clean)[match(seq(Start.wave, 
       End.wave, 1), names(lopex_dat_clean))]) at nph16123-sup-0002-MethodsS1.R#121
5: lopex_dat_clean[, names(lopex_dat_clean)[match(seq(Start.wave, 
       End.wave, 1), names(lopex_dat_clean))]] at nph16123-sup-0002-MethodsS1.R#121
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("~/Downloads/serbinsh-SSerbin_etal_2019_NewPhytologist-9cf6ce3/nph16123-sup-0002-MethodsS1.R")
> head(dat_raw)
# A tibble: 6 x 1
  `<!DOCTYPE html>`                           
  <chr>                                       
1 <html>                                      
2 <!--[if lte IE 10]>                         
3 "<script type=\"text/javascript\">"         
4 if ( document.URL.indexOf( 'ie' ) === -1 ) {
5 window.location = '/ie.html';               
6 }                                         
```

**Comment by serbinsh** [comment]
Yeah, so it looks like the old way I constructed the URL strings no longer works?

https://ecosis.org/package/export?package_id=2231d4f6-981e-4408-bf23-1b2b303f475e&filters=&metadata=true

that goes to an undefined package on EcoSIS

If I try this I get:

```
ecosis_file <- 'https://ecosis.org/api/package/leaf-optical-properties-experiment-database--lopex93-'
message("Downloading data...")
dat_raw <- read_csv(ecosis_file)
message("Download complete!")

# A tibble: 0 x 2,212
# … with 2,212 variables: `{"_id":"13aef0ce-dd6f-4b35-91d9-28932e506c41"` <chr>, `Author Email":["brian.hosgood@jrc.it"],"Processing
#   Interpolated":["yes"],"Measurement Quantity":["reflectance` <chr>, `transmittance"],"Maintainer Email":["amazur@wisc.edu"],"Location
#   Name":["joint research centre` <chr>, `institute for remote sensing applications` <chr>, `ispra - italy"],"Light Source
#   Specifications":["uv: deuterium lamp` <chr>, `vis/nir: tungsten-halogen lamp"],"Sample Platform":["table top"],"Processing
#   Averaged":["no"],"Year":["1993"],"Website":["http://opticleaf.ipgp.fr/index.php?page=home"],"Keywords":["anthocyanin` <chr>,
#   carbon <chr>, carotenoid <chr>, cellulose <chr>, `chlorophyll a` <chr>, `chlorophyll b` <chr>, hydrogen <chr>, lignin <chr>, lma <chr>,
#   nitrogen <chr>, oxygen <chr>, protein <chr>, reflectance <chr>, starch <chr>, `transmittance"],"Instrument Manufacturer":["perkin
#   elmer"],"Processing Resampled":["yes"],"Ecosystem Type":["crops` <chr>, forest <chr>, `grassland"],"Acquisition
#   Method":["contact"],"Citation":["B. Hosgood S. Jacquemound G. Andreeoli J. Verdebout A. Pedrini G. Schmuck. 1993. Leaf Optical Properties
#   Experiment Database (LOPEX93). Data set. Available on-line [http://ecosis.org] from the Ecological Spectral Information System
#   (EcoSIS)"],"Measurement Venue":["laboratory"],"Foreoptic Type":["integrating sphere"],"Maintainer":["aidan mazur"],"Wavelength
#   Units":["other"],"Target Status":["green` <chr>, `fresh"],"Instrument Model":["lambda-19
#   spectrophotometer"],"ecosis":{"sort_type":"numeric` <chr>, `license":"Other (Open)` <chr>, `package_title":"Leaf Optical Properties
#   Experiment Database (LOPEX93)` <chr>, `description":"An experiment was organized in the Joint Research Centre at Ispra during the summer
#   of 1993 in which a data set associating visible / infrared spectra of vegetation elements with physical measurements and biochemical
#   analyses was constructed. Reflectance and transmittance measurements of 330 Leaf samples from 45 different species with associated
#   metadata are provided. See linked resources for more information regarding LOPEX93` <chr>,
#   `package_name":"leaf-optical-properties-experiment-database--lopex93-` <chr>, `created":"2016-10-31T21:46:24.959Z` <chr>,
#   `sort_on":"Carbon` <chr>, `modified":"2016-12-19T20:51:10.592Z` <chr>, `geojson":{"type":"GeometryCollection` <chr>,
#   `geometries":[{"type":"Polygon` <chr>,
#   `coordinates:[[[8.630018234252928,45.80741830070185],[8.630018234252928,45.80564580302376],[8.632614612579346,45.80564580302376],[8.632614612579346,45.80741830070185],[8.630018234252928,45.80741830070185]]]}]},"sort_description:","organization_id:"aa184fd1-230a-40b3-a585-e590fd1219e8` <chr>,
#   `pushed":"2016-12-19T20:51:29.308Z` <chr>, `package_id":"13aef0ce-dd6f-4b35-91d9-28932e506c41` <chr>, `version":"1.0` <chr>,
#   `spectra_metadata_schema":{"units":{"Protein_1":"% DW` <chr>, `Protein_2":"% DW` <chr>, `Chlorophyll_a":"µg/cm²` <chr>,
#   `Chlorophyll_b":"µg/cm²` <chr>, `Location : Ispra":"Italy` <chr>, `Leaf mass per area":"g/cm²` <chr>, `Equivalent Water
#   Thickness":"g/cm²` <chr>, `Dry Weight":"g` <chr>, `Carbon":"% DW` <chr>, `Oxygen":"% DW` <chr>, `Carotenoid":"µg/cm²` <chr>,
#   `Starch_1":"% DW` <chr>, `Starch_2":"% DW` <chr>, `Cellulose_1":"% DW` <chr>, `Cellulose_2":"% DW` <chr>, `Fresh Weight":"g` <chr>,
#   `Lignin_2":"% DW` <chr>, `Lignin_1":"% DW` <chr>, `Chlorophyll_a+b":"µg/cm²` <chr>, `Leaf Area":"cm²` <chr>, `Leaf Thickness":"µm` <chr>,
#   `Nitrogen":"% DW` <chr>, `Hydrogen":"% DW` <chr>, `LOPEX leaf optical properties database":"June-October
#   1993"},"wavelengths":["400` <chr>, `401` <chr>, `402` <chr>, `403` <chr>, `404` <chr>, `405` <chr>, `406` <chr>, `407` <chr>,
#   `408` <chr>, `409` <chr>, `410` <chr>, `411` <chr>, `412` <chr>, `413` <chr>, `414` <chr>, `415` <chr>, `416` <chr>, `417` <chr>,
#   `418` <chr>, `419` <chr>, `420` <chr>, `421` <chr>, `422` <chr>, `423` <chr>, `424` <chr>, `425` <chr>, `426` <chr>, `427` <chr>,
#   `428` <chr>, `429` <chr>, `430` <chr>, `431` <chr>, `432` <chr>, `433` <chr>, `434` <chr>, `435` <chr>, `436` <chr>, `437` <chr>,
#   `438` <chr>, `439` <chr>, `440` <chr>, …```

So its not parsing that either.....

**Comment by jrmerz** [comment]
Shawn, we just update the EcoSIS API to fit a more standard REST API format.  We have also update urls for better SEO performance as well as to be better web stewards.  That said...

## Browser Access

Packages are now access via name: 
https://ecosis.org/package/angers-leaf-optical-properties-database--2003-
Or id (though name is preferred):
https://ecosis.org/package/13aef0ce-dd6f-4b35-91d9-28932e506c41

The old JavaScript urls (with a '#' in it):
https://ecosis.org/#result/2231d4f6-981e-4408-bf23-1b2b303f475e
will redirect to the new urls.

## API (REST) Access

The API urls have change as well.  See below.

Package Metadata:
https://ecosis.org/api/package/[package-name]
https://ecosis.org/api/package/angers-leaf-optical-properties-database--2003-

Package Download:
https://ecosis.org/api/package/[package-name]/export
https://ecosis.org/api/package/angers-leaf-optical-properties-database--2003-/export
https://ecosis.org/api/package/angers-leaf-optical-properties-database--2003-/export?metadata=true

Package Spectra Search:
https://ecosis.org/api/spectra/search/[package-id]?text=&filters=%5B%5D&start=1&stop=2
https://ecosis.org/api/spectra/search/angers-leaf-optical-properties-database--2003-?text=&filters=%5B%5D&start=0&stop=1

I am still working on updating the API documentation.  Please let me know if you have any further questions.

**Comment by jrmerz** [comment]
If required, I can look to add a redirect for the old API url.  Though I would not be my preference.

**Comment by serbinsh** [comment]
@jrmerz OK, thanks for the update.  The problem I have is that the code is already part of an Early View manuscript so I am not sure if I can get the file updated.  If not, that means the code provided with the paper is broken.  I will update the example script and email the Journal to see if I can get the file switched out before final publication.  

This perhaps raises a larger issue of back compatibility in the future.  I want to use EcoSIS to serve up datasets used in pubs but if there is a risk things change enough to break code, that isnt great for posterity.  I get things are getting updated to make them better and perhaps there arent that many heavy EcoSIS users yet but in the future this could cause more issues than just my example here.

Also I would push back against your "name is preferred" statement or at least ask why?  Seems to me name is fickle, especially if it gets modified, however the ID is always the same once created correct?  So in terms of embedded links to datasets, etc, it seems to me ID is the way to go yes?  I also see how the names right now have a hanging "-" on them and if that got removed in an update would the connection break?

Finally, is there a development schedule/plan?  I suppose if I new this change was coming I could have asked if I needed to make any changes before sending my code to the journal so it was "future proof"

Sorry for the barrage, but I appreciate the help and feedback!

**Comment by serbinsh** [comment]
@jrmerz Do you see any issues changing the code like below to use the new API URL?

```
library(readr)
#--------------------------------------------------------------------------------------------------#
### Grab data
print("**** Downloading Ecosis data ****")
ecosis_id <- "13aef0ce-dd6f-4b35-91d9-28932e506c41"  # lopex
ecosis_file <- sprintf(
  "https://ecosis.org/api/package/%s/export?metadata=true",
  ecosis_id
)

message("Downloading data...")
dat_raw <- read_csv(ecosis_file)
message("Download complete!")

# keep just fresh leaf refl obs. remove dried leaves from sample set
remove <- c(176,177,178,179,180,196,197,198,199,200,321,322,323,324,325)
remove <- which(dat_raw$Measurement_type=="transmittance" | dat_raw$`Sample_#` %in% remove)
lopex_dat_clean <- dat_raw[-remove,]

ecosis_id <- "2231d4f6-981e-4408-bf23-1b2b303f475e"  # angers
ecosis_file <- sprintf(
  "https://ecosis.org/api/package/%s/export?metadata=true",
  ecosis_id
)

message("Downloading data...")
dat_raw <- read_csv(ecosis_file)
message("Download complete!")

# cleanup and remove dried leaves from dataset
remove <- c(178,179,184,185,196,197,241,250,254,257,258,269)
remove <- which(dat_raw$Measurement_type=="transmittance" | dat_raw$`Sample_#` %in% remove)
angers_dat_clean <- dat_raw[-remove,]

rm(dat_raw)
#--------------------------------------------------------------------------------------------------#
```

In R this should get the data, I have tested and it seems to fix the issues with my script

**Comment by serbinsh** [comment]
I am updating my repo here: https://github.com/serbinsh/SSerbin_etal_2019_NewPhytologist

I have also emailed the journal to see if they can replace the previous file with the new one containing the new URLs that now work with the latest API

**Comment by jrmerz** [comment]
@serbinsh All of your points are valid.  I promise things have moved to a stable state and the painful transition has more to due with limited resourcing than anything else.  The API is documented as alpha and subject to change (http://cstars.github.io/ecosis/).  This alpha label will be removed and the API will now be in a frozen state.  That said I will go and add support for the old API as it was a bit of an oversight on my part to the level of production usage for the EcoSIS API.

As for names vs ids.  There are lots of articles on the web about why 'friendly' urls are preferred. Here is one from Google (https://support.google.com/webmasters/answer/7451184?hl=en).  The EcoSIS ID is still supported if you are afraid you will change the name of your dataset in the future.  One issue with EcoSIS Id's is that they have no meaning outside the EcoSIS system.  Obviously that's why we have ID systems such as DOIs/ARKs.  And to that end, EcoSIS has a new feature that we need to advertise and I would recommend using for papers; EcoSIS resolves registered DOIs.  Ex: https://ecosis.org/doi:10.21232/C22M27 (one of your datasets I believe).  Currently this feature is only available for EcoSIS assigned DOIs.  But could be expanded to support any provided DOI.  Obviously using the DOI link has a lot of staying power and meaning.

As for notification of changes, I am happy to notify you and all changes are on dev (https://dev-search.ecosis.org) for some time before they are rolled out to production.  This overhaul was a long time coming and as stated above will put path names in a frozen state.  There were some poor decisions made early on on this front by me, but the ship has now been righted.  Please let me know if you have any further questions.

**Comment by serbinsh** [comment]
@jrmerz No worries, I get it.  I think I was taken off guard but the fix seems to have been quick and easy!  And I think the Journal is going to correct the file on the final version, so should be good to go now.  Finally, I have updated my git repo and ecosml here: https://ecosml.org/package/a96e0cd7-1d9a-490f-906f-bff1148f05a9 . BTW great to see that up and running now, even if just in Alpha!  Pretty cool!

I also need to keep tabs on the dev stuff more in the future since I want our lab to use EcoSIS more.  I think I now have a pretty good handle on EcoSIS and the ecosml system so that should be easy.  

Finally, I didnt know about the DOI resolving but that is also very cool.  I think supporting external DOIs is a great idea since some of the data we collect needs to get a DOI from the DOE database, but as I have done before I then use that with my EcoSIS entry.  

I think the changes are very good and now they are "frozen" more or less I think I wont have this issue moving forward.

Again thanks for the detailed feedback and help.  Shall we close this?

**Comment by jrmerz** [comment]
Great to see you using EcoSML!  Another drive for the new update was tighter integration between EcoSIS and EcoSML in the client interface(s). You may have noticed that EcoSML is now a first class citizen of EcoSIS being both mentioned on the front page and linked to in the main nav.  The visual branding is also similar.

Effort will now move to move to making EcoSML closer to the new EcoSIS look and feel as well as link integration.

Closing the issue.
