### ISSUE TITLE
Linking Data where sample number reaches wavelength 

### ISSUE THREAD

**Issue by walther3** [CSTARS/ecosis#39]
For data set "Leaf and canopy level detection of Fusarium virguliforme (sudden death syndrome) in soybean" there is an issue with the data and metadata properly linking. The sample number started to exceed reach the same values as the wavelengths so metadata started to link to the wavelength and not the sample. 

<img width="1680" alt="Screen Shot 2019-10-01 at 1 23 53 PM" src="https://user-images.githubusercontent.com/55326013/65989155-bf534c00-e44e-11e9-8e30-baf630981bad.png">

**Comment by jrmerz** [comment]
Couple things.  First, the screen shot above is not properly formatted tabular data.  Second, the screen shot does not match any of the sheets in data.ecosis.org (https://data.ecosis.org/dataset/leaf-and-canopy-level-detection-of-fusarium-virguliforme--sudden-death-syndrome--in-soybean).

Can you point me at the example where you are seeing this issue in EcoSIS?

**Comment by walther3** [comment]
<img width="1680" alt="Screen Shot 2019-10-01 at 2 58 47 PM" src="https://user-images.githubusercontent.com/55326013/65995923-098efa00-e45c-11e9-8398-e863ff80a1e5.png">
When I download the data in a single .csv file from the page above the previous screenshot is what appears

**Comment by jrmerz** [comment]
Thanks, I see the issue now.  Looking into it.

**Comment by jrmerz** [comment]
It looks like many changes were made to this dataset on data.ecosis.org and never pushed to search (ecosis.org).  I have re-published the dataset and everything looks ok now.  Pleas re-open if you see an issue.
