### ISSUE TITLE
Explicit data license

### ISSUE THREAD

**Issue by jpolchlo** [CSTARS/ecosis#53]
I have downloaded data from EcoSIS and want to know what the restrictions are for its use.  Can I, for example, include spectral data in examples in Github repositories?  Is there a release signed by contributors to EcoSIS describing their rights and limitations prior to uploading data?  I'd appreciate if this information were called out clearly and explicitly on the website.  Please let me know if I missed it!  Thanks for your good works.

**Comment by jrmerz** [comment]
@jpolchlo this is a great point and the license information does need to be displayed on the main site.  License information is provided by uploader of the dataset.  You can find that information here https://data.ecosis.org/, which is the data maintainers portal.  If you search for the dataset, the landing page will show the selected license.

I look to add the license information to the main site.

**Comment by jpolchlo** [comment]
Thanks for the quick response.  Good to know that some datasets have a visible license.  For those entries without one listed, is there a default?  Can contributors specify closed licenses (as paradoxical as that would be for uploading data to a public repo)?

**Comment by jrmerz** [comment]
More good questions.  There is no default. The EcoSIS team will be debating requiring licenses and reaching out to those without licenses asking them to provide one.  If you are currently interested in a dataset without a license, I would encourage you to reach out to the organization and ask them to provide one.  

There is a an option for a closed license.  Paradoxical indeed.  Luckily EcoSIS has only have one dataset marked as such and the EcoSIS team is debating the removal of that option.

**Comment by jpolchlo** [comment]
OK.  Thanks.  And thanks for your work.  I'm satisfied with these answers and hope to see more uptake of this platform in the future!

**Comment by jrmerz** [comment]
Licenses are now showing on ecosis.org.  Further discussions about requiring a license will be moved to another issue.
